### PR TITLE
CodeMaid

### PR DESCRIPTION
**Pull request by roku674**
Arranged everything by Public/Internal/Protected/private Arranged everything by ABC Order
Uniform spacing and line breaks

this was going to bug me since the project is so big

### CODE REVIEW

**Comment by roku674** [comment]
@RevenantX

**Comment by RevenantX** [comment]
it changed only whitespaces and in some places in bad way.

**Comment by roku674** [comment]
> it changed only whitespaces and in some places in bad way.

ruh roh i'll have to take a look after work today (mostly was just trying to get things in ABC Order)

**Comment by roku674** [comment]
closing till I figure out how to not get CodeMaid to not change spacing

**Pull request closed without merging**
